server:
  port: 8500
  
spring:
  application:
    name: comunicado-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
  server:
    wait-time-in-ms-when-sync-empty: 3000
  
ribbon:
  eureka:
    enabled: true